## Introduction
#### Text Files

In [1]:
f = open('textfile.txt', 'r')
content = f.read()
print(content)
f.close()

Hello, world!

In [2]:
with open('textfile.txt', 'r') as f:
    content = f.read()
print(content)

Hello, world!

In [3]:
with open('textmultilines.txt', 'r') as f:
    lines = f.readlines()
    for line in lines:
        print(line)

Hello, world!

This is the second line.

This is the end of the file.

In [1]:
with open('newfile.txt', 'w') as f:
    f.write('Hello, world!')

!cat newfile.txt

Hello, world!

In [2]:
with open('newfile.txt', 'a') as f:
    f.write('\nThis is a new line.')

!cat newfile.txt

Hello, world!
This is a new line.

## Table Data
#### CSV(TSV)

In [3]:
newlist = []

with open('sample_data.csv', 'r') as f:
    lines = f.readlines()
    for line in lines:
        info = line.strip().split(',')
        if info[0] == 'id':
            continue
        newlist.append(info)

for line in newlist:
    print(line)

['1', 'Alice', '23', 'NY', '88']
['2', 'Bob', '34', 'LA', '92']
['3', 'Charlie', '29', 'SF', '79']
['4', 'Diana', '42', 'CHI', '85']
['5', 'Ethan', '31', 'HOU', '90']
['6', 'Fiona', '27', 'PHX', '76']
['7', 'George', '36', 'SEA', '95']
['8', 'Hannah', '30', 'MIA', '89']
['9', 'Ian', '25', 'DEN', '84']
['10', 'Jane', '40', 'BOS', '91']

In [4]:
import csv # Python 내장 라이브러리

# csv 파일 열기
with open('sample_data.tsv', 'r') as f:
    # csv.reader: csv 파일의 내용을 읽어들여 레코드와 필드로 나누어 줌
    reader = csv.reader(f, delimiter='\t')

    print(reader)
    print(list(reader))

<_csv.reader object at 0x70d53902c4a0>
[['id', 'name', 'age', 'city', 'score'], ['1', 'Alice', '23', 'NY', '88'], ['2', 'Bob', '34', 'LA', '92'], ['3', 'Charlie', '29', 'SF', '79'], ['4', 'Diana', '42', 'CHI', '85'], ['5', 'Ethan', '31', 'HOU', '90'], ['6', 'Fiona', '27', 'PHX', '76'], ['7', 'George', '36', 'SEA', '95'], ['8', 'Hannah', '30', 'MIA', '89'], ['9', 'Ian', '25', 'DEN', '84'], ['10', 'Jane', '40', 'BOS', '91']]

In [5]:
with open('sample_data.tsv', 'r') as f:
    reader = csv.reader(f, delimiter='\t')

    for record in reader:
        print(record)

['id', 'name', 'age', 'city', 'score']
['1', 'Alice', '23', 'NY', '88']
['2', 'Bob', '34', 'LA', '92']
['3', 'Charlie', '29', 'SF', '79']
['4', 'Diana', '42', 'CHI', '85']
['5', 'Ethan', '31', 'HOU', '90']
['6', 'Fiona', '27', 'PHX', '76']
['7', 'George', '36', 'SEA', '95']
['8', 'Hannah', '30', 'MIA', '89']
['9', 'Ian', '25', 'DEN', '84']
['10', 'Jane', '40', 'BOS', '91']

In [6]:
with open('sample_data.tsv', 'r') as f:
    reader = csv.reader(f, delimiter='\t')
    next(reader) # 첫번째 행을 건너뛰고 다음 행부터 접근

    for record in reader:
        print(record)

['1', 'Alice', '23', 'NY', '88']
['2', 'Bob', '34', 'LA', '92']
['3', 'Charlie', '29', 'SF', '79']
['4', 'Diana', '42', 'CHI', '85']
['5', 'Ethan', '31', 'HOU', '90']
['6', 'Fiona', '27', 'PHX', '76']
['7', 'George', '36', 'SEA', '95']
['8', 'Hannah', '30', 'MIA', '89']
['9', 'Ian', '25', 'DEN', '84']
['10', 'Jane', '40', 'BOS', '91']

In [7]:
# 잘못된 구분자를 사용하면 필드를 올바르게 나눌 수 없다.

with open('sample_data.tsv', 'r') as f:
    reader = csv.reader(f, delimiter=',')
    next(reader)

    for record in reader:
        print(record)

['1\tAlice\t23\tNY\t88']
['2\tBob\t34\tLA\t92']
['3\tCharlie\t29\tSF\t79']
['4\tDiana\t42\tCHI\t85']
['5\tEthan\t31\tHOU\t90']
['6\tFiona\t27\tPHX\t76']
['7\tGeorge\t36\tSEA\t95']
['8\tHannah\t30\tMIA\t89']
['9\tIan\t25\tDEN\t84']
['10\tJane\t40\tBOS\t91']

In [8]:
with open('sample_data.csv', 'r') as f:
    reader = csv.reader(f, delimiter='\t')
    next(reader)

    for record in reader:
        print(record)

['1,Alice,23,NY,88']
['2,Bob,34,LA,92']
['3,Charlie,29,SF,79']
['4,Diana,42,CHI,85']
['5,Ethan,31,HOU,90']
['6,Fiona,27,PHX,76']
['7,George,36,SEA,95']
['8,Hannah,30,MIA,89']
['9,Ian,25,DEN,84']
['10,Jane,40,BOS,91']

In [10]:
with open('sample_new.csv', 'w') as f:
    writer = csv.writer(f, delimiter=',') # csv.writer 설정: 파일에 쓰기 준비
    writer.writerow(['id', 'name', 'age']) # 레코드 하나씩을 파일에 쓴다
    writer.writerow(['1', 'Alice', '25']) # 리스트의 원소 하나가 필드 하나에 대응
    writer.writerow(['2', 'Bob', '30'])
    writer.writerow(['3', 'Candy', '27'])

!cat sample_new.csv

id,name,age
1,Alice,25
2,Bob,30
3,Candy,27

#### DataFrame

In [13]:
!pip install pandas
import pandas as pd

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 37.6 MB/s  0:00:006m0:00:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 35.3 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.5

In [14]:
df = pd.read_csv('sample_data/california_housing_test.csv')

df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [15]:
# Dict에서 DataFrame으로

dict1 = {
    "A": 1.0,
    "B": pd.Timestamp("20211201"),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D": [3]*4,
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo",
}
pd.DataFrame(dict1)

     A          B    C  D      E    F
0  1.0 2021-12-01  1.0  3   test  foo
1  1.0 2021-12-01  1.0  3  train  foo
2  1.0 2021-12-01  1.0  3   test  foo
3  1.0 2021-12-01  1.0  3  train  foo

In [16]:
pd.DataFrame.from_dict(dict1)

     A          B    C  D      E    F
0  1.0 2021-12-01  1.0  3   test  foo
1  1.0 2021-12-01  1.0  3  train  foo
2  1.0 2021-12-01  1.0  3   test  foo
3  1.0 2021-12-01  1.0  3  train  foo

In [18]:
df = pd.read_csv('sample_data/california_housing_test.csv')

print(type(df))

!head sample_data/california_housing_test.csv

<class 'pandas.DataFrame'>
"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"
-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000
-118.300000,34.260000,43.000000,1510.000000,310.000000,809.000000,277.000000,3.599000,176500.000000
-117.810000,33.780000,27.000000,3589.000000,507.000000,1484.000000,495.000000,5.793400,270500.000000
-118.360000,33.820000,28.000000,67.000000,15.000000,49.000000,11.000000,6.135900,330000.000000
-119.670000,36.330000,19.000000,1241.000000,244.000000,850.000000,237.000000,2.937500,81700.000000
-119.560000,36.510000,37.000000,1018.000000,213.000000,663.000000,204.000000,1.663500,67000.000000
-121.430000,38.630000,43.000000,1009.000000,225.000000,604.000000,218.000000,1.664100,67000.000000
-120.650000,35.480000,19.000000,2310.000000,471.000000,1341.000000,441.000000,3.225000,166900.000000
-122.840000,38.400000,15.000000,3080.000000,617.000000,1446.000000,599.000000,3.669600,194400.000000

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('sample_data/california_housing_test.csv')

df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

#### Pandas Quick Glance

In [23]:
df.index

RangeIndex(start=0, stop=3000, step=1)

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='str')

In [26]:
df['longitude']

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [25]:
df.iloc[200]

longitude              -123.280
latitude                 40.770
housing_median_age       25.000
total_rooms             767.000
total_bedrooms          206.000
population              301.000
households              121.000
median_income             1.625
median_house_value    79200.000
Name: 200, dtype: float64

In [27]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [28]:
df.tail(7)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [29]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [30]:
df.mean()

longitude               -119.589200
latitude                  35.635390
housing_median_age        28.845333
total_rooms             2599.578667
total_bedrooms           529.950667
population              1402.798667
households               489.912000
median_income              3.807272
median_house_value    205846.275000
dtype: float64

In [31]:
df.std()

longitude                  1.994936
latitude                   2.129670
housing_median_age        12.555396
total_rooms             2155.593332
total_bedrooms           415.654368
population              1030.543012
households               365.422710
median_income              1.854512
median_house_value    113119.687470
dtype: float64

In [32]:
df[['longitude', 'latitude']].mean()

longitude   -119.58920
latitude      35.63539
dtype: float64

In [33]:
df.iloc[10:15]['households']

10    261.0
11    138.0
12    170.0
13    659.0
14    331.0
Name: households, dtype: float64

## Attribute-Value Data
#### JSON

In [37]:
j_str = '{"name": "Alice", "age": 23, "job": "student"}'

print(j_str)

{"name": "Alice", "age": 23, "job": "student"}

In [38]:
import json

j = json.loads(j_str)

print(type(j))

<class 'dict'>

In [39]:
!cat samplej.json

{
  "company": {
    "name": "TechCorp",
    "location": "New York",
    "departments": {
      "engineering": {
        "manager": "Alice",
        "teams": [
          {
            "name": "Backend",
            "members": ["Bob", "Charlie"]
          },
          {
            "name": "Frontend",
            "members": ["Diana", "Ethan"]
          }
        ]
      },
      "hr": {
        "manager": "Fiona",
        "teams": [
          {
            "name": "Recruitment",
            "members": ["George", "Hannah"]
          }
        ]
      }
    }
  }
}

In [40]:
import json

with open('samplej.json', 'r') as f:
    content = json.load(f)
    print(content)

{'company': {'name': 'TechCorp', 'location': 'New York', 'departments': {'engineering': {'manager': 'Alice', 'teams': [{'name': 'Backend', 'members': ['Bob', 'Charlie']}, {'name': 'Frontend', 'members': ['Diana', 'Ethan']}]}, 'hr': {'manager': 'Fiona', 'teams': [{'name': 'Recruitment', 'members': ['George', 'Hannah']}]}}}}

In [41]:
print(content['company'])
print(content['company']['departments'].keys())
print(len(content['company']['departments']['engineering']['teams']))

{'name': 'TechCorp', 'location': 'New York', 'departments': {'engineering': {'manager': 'Alice', 'teams': [{'name': 'Backend', 'members': ['Bob', 'Charlie']}, {'name': 'Frontend', 'members': ['Diana', 'Ethan']}]}, 'hr': {'manager': 'Fiona', 'teams': [{'name': 'Recruitment', 'members': ['George', 'Hannah']}]}}}
dict_keys(['engineering', 'hr'])
2

In [43]:
content

{'company': {'name': 'TechCorp',
  'location': 'New York',
  'departments': {'engineering': {'manager': 'Alice',
    'teams': [{'name': 'Backend', 'members': ['Bob', 'Charlie']},
     {'name': 'Frontend', 'members': ['Diana', 'Ethan']}]},
   'hr': {'manager': 'Fiona',
    'teams': [{'name': 'Recruitment', 'members': ['George', 'Hannah']}]}}}}

In [42]:
content['company']['departments'].keys()

dict_keys(['engineering', 'hr'])

In [44]:
content['company']['departments']['homeprotector'] = {'manager': 'Sana', 'teams': []}
content['company']['departments'].keys()

dict_keys(['engineering', 'hr', 'homeprotector'])

In [45]:
content['company']['departments']['hr']['manager'] = 'Melissa'
content

{'company': {'name': 'TechCorp',
  'location': 'New York',
  'departments': {'engineering': {'manager': 'Alice',
    'teams': [{'name': 'Backend', 'members': ['Bob', 'Charlie']},
     {'name': 'Frontend', 'members': ['Diana', 'Ethan']}]},
   'hr': {'manager': 'Melissa',
    'teams': [{'name': 'Recruitment', 'members': ['George', 'Hannah']}]},
   'homeprotector': {'manager': 'Sana', 'teams': []}}}}

In [46]:
with open('content_edit.json', 'w') as f:
    json.dump(content, f, indent=4, ensure_ascii=False)

!cat content_edit.json

{
    "company": {
        "name": "TechCorp",
        "location": "New York",
        "departments": {
            "engineering": {
                "manager": "Alice",
                "teams": [
                    {
                        "name": "Backend",
                        "members": [
                            "Bob",
                            "Charlie"
                        ]
                    },
                    {
                        "name": "Frontend",
                        "members": [
                            "Diana",
                            "Ethan"
                        ]
                    }
                ]
            },
            "hr": {
                "manager": "Melissa",
                "teams": [
                    {
                        "name": "Recruitment",
                        "members": [
                            "George",
                            "Hannah"
                        ]
                    }
                ]
            },
            "homeprotector": {
                "manager": "Sana",
                "teams": []
            }
        }
    }
}

In [47]:
content['company']['departments']['hr']['manager'] = '민병관'
content

{'company': {'name': 'TechCorp',
  'location': 'New York',
  'departments': {'engineering': {'manager': 'Alice',
    'teams': [{'name': 'Backend', 'members': ['Bob', 'Charlie']},
     {'name': 'Frontend', 'members': ['Diana', 'Ethan']}]},
   'hr': {'manager': '민병관',
    'teams': [{'name': 'Recruitment', 'members': ['George', 'Hannah']}]},
   'homeprotector': {'manager': 'Sana', 'teams': []}}}}

In [49]:
with open('content_edit.json', 'w') as f:
    json.dump(content, f, indent=4)

!cat content_edit.json

{
    "company": {
        "name": "TechCorp",
        "location": "New York",
        "departments": {
            "engineering": {
                "manager": "Alice",
                "teams": [
                    {
                        "name": "Backend",
                        "members": [
                            "Bob",
                            "Charlie"
                        ]
                    },
                    {
                        "name": "Frontend",
                        "members": [
                            "Diana",
                            "Ethan"
                        ]
                    }
                ]
            },
            "hr": {
                "manager": "\ubbfc\ubcd1\uad00",
                "teams": [
                    {
                        "name": "Recruitment",
                        "members": [
                            "George",
                            "Hannah"
                        ]
                    }
                ]
            },
            "homeprotector": {
                "manager": "Sana",
                "teams": []
            }
        }
    }
}

#### JSONL

In [50]:
!cat samplelines.jsonl

{"id": 1, "name": "Alice", "scores": {"math": 90, "english": 85}}
{"id": 2, "name": "Bob", "scores": {"math": 78, "english": 88}}
{"id": 3, "name": "Charlie", "scores": {"math": 92, "english": 81}}
{"id": 4, "name": "Diana", "scores": {"math": 85, "english": 95}}
{"id": 5, "name": "Ethan", "scores": {"math": 80, "english": 89}}

In [52]:
with open('samplelines.jsonl', 'r') as f:
    lines = f.readlines()
    for line in lines:
        j = json.loads(line)
        print(type(j), j['name'], j['scores']['english'])

<class 'dict'> Alice 85
<class 'dict'> Bob 88
<class 'dict'> Charlie 81
<class 'dict'> Diana 95
<class 'dict'> Ethan 89

## Auxiliaries
#### Text Encoding

In [53]:
s = '언컴'
s_utf8 = s.encode('utf-8')
print(s_utf8)

b'\xec\x96\xb8\xec\xbb\xb4'

In [54]:
s_org = s_utf8.decode()
print(s_org)

언컴

In [55]:
b'\xec\x96\xb8'.decode()

'언'

In [56]:
c = '가'
print(ord(c)) # 문자의 유니코드 값 얻기
print(hex(ord(c))) # 유니코드 값 16진수로 표현하기
print(chr(44032)) # 유니코드 값에 해당하는 문자 얻기

44032
0xac00
가

In [57]:
s = 'hi😊'
print(s.encode('utf-8'))

b'hi\xf0\x9f\x98\x8a'

In [62]:
!pip install chardet
!chardetect cp949-utf8.txt

Collecting chardet
  Downloading chardet-7.6.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Downloading chardet-7.6.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 6.1 MB/s  0:00:0036m-:--:--
Installing collected packages: chardet
Successfully installed chardet-7.6.0
cp949-utf8.txt: utf-8 with confidence 0.99

In [63]:
!chardetect euc_kr.txt

euc_kr.txt: EUC-KR with confidence 1.0

iconv -f {출발 인코딩} -t {도착 인코딩} {파일명} > {새로 쓸 파일명}

In [66]:
!iconv -f euc-kr -t utf-8 euc_kr.txt > new_file.txt

In [67]:
!cat euc_kr.txt

�� ���̽�(Python)�� ���� ����, ������ ���α׷��� ����Դϴ�. ���̽���
ȿ������ ������ ������ ������ ���������� ȿ������ ��ü�������α׷�����
�����մϴ�. ���̽��� ���(���)�� ������ ���� Ÿ����, �׸��� ����������
ȯ���� ���̽��� ��ũ���ð� ���� �о߿����� ��κ��� �÷��������� ����
���ø����̼� ������ �� �� �ִ� �̻����� ���� ������ݴϴ�.

��ù����: ���ƶ� �Ԥ��ФԤԤ��ФԾ�~ �Ԥ��Ҥ�ŭ! �Ԥ��Ѥ��ݾ��� ���Ԥ��Ȥ��ϴ�. �Ԥ��Τ�. �׷��� �Ԥ��Ѥ���.

In [68]:
!chardetect new_file.txt

new_file.txt: utf-8 with confidence 0.99

In [69]:
!cat new_file.txt

◎ 파이썬(Python)은 배우기 쉽고, 강력한 프로그래밍 언어입니다. 파이썬은
효율적인 고수준 데이터 구조와 간단하지만 효율적인 객체지향프로그래밍을
지원합니다. 파이썬의 우아(優雅)한 문법과 동적 타이핑, 그리고 인터프리팅
환경은 파이썬을 스크립팅과 여러 분야에서와 대부분의 플랫폼에서의 빠른
애플리케이션 개발을 할 수 있는 이상적인 언어로 만들어줍니다.

☆첫가끝: 날아라 ㅤㅆㅠㅤㅤㅆㅠㅤ쓩~ ㅤㄴㅢㅇ큼! ㅤㄸㅡㅇ금없이 전ㅤㅎㅘㅂ니다. ㅤㅂㅞㄺ. 그런거 ㅤㅇㅡㅄ다.

In [70]:
s = open('euc_kr.txt', 'r', encoding='euc-kr').read()
print(s)

◎ 파이썬(Python)은 배우기 쉽고, 강력한 프로그래밍 언어입니다. 파이썬은
효율적인 고수준 데이터 구조와 간단하지만 효율적인 객체지향프로그래밍을
지원합니다. 파이썬의 우아(優雅)한 문법과 동적 타이핑, 그리고 인터프리팅
환경은 파이썬을 스크립팅과 여러 분야에서와 대부분의 플랫폼에서의 빠른
애플리케이션 개발을 할 수 있는 이상적인 언어로 만들어줍니다.

☆첫가끝: 날아라 쓔쓔쓩~ 닁큼! 뜽금없이 전홥니다. 뷁. 그런거 읎다.

In [71]:
f = open('new_encoding.txt', 'w', encoding='utf-8')
f.write(s)
f.close()

!chardetect new_encoding.txt

new_encoding.txt: utf-8 with confidence 0.99

#### Object File: pickle

In [72]:
import random
import pickle

In [73]:
randlist = random.sample(range(1, 10000), 1000)
# 길이 1000인 리스트
print(randlist)

[1372, 7392, 9046, 1933, 3632, 271, 7110, 3813, 8456, 7248, 6539, 7840, 6622, 11, 9961, 4945, 8376, 5017, 5894, 18, 4450, 4380, 3434, 3660, 6710, 8174, 5332, 9809, 3990, 2289, 8590, 2251, 2713, 5016, 4105, 9545, 477, 496, 6761, 3573, 9940, 3215, 9782, 1308, 8863, 4625, 6276, 2624, 7508, 8595, 2411, 8602, 3677, 6629, 2499, 5706, 8580, 911, 4785, 6469, 4015, 7174, 4784, 49, 5557, 2243, 9682, 9395, 5436, 2419, 8095, 1895, 1194, 3689, 4765, 2908, 1705, 8836, 5364, 3818, 3745, 6028, 9274, 7031, 3714, 1822, 8014, 7495, 5322, 1474, 1590, 8705, 2106, 8671, 1587, 439, 4614, 1187, 4679, 6361, 4027, 5094, 7445, 6839, 2853, 943, 4133, 8307, 4011, 3631, 2528, 8760, 7752, 9344, 7340, 5889, 3288, 7940, 8112, 7491, 3444, 4220, 470, 1768, 7589, 7989, 6696, 9881, 9467, 2035, 9446, 6198, 233, 2426, 3952, 6962, 2860, 1791, 4514, 2690, 465, 6338, 7423, 9850, 7606, 6246, 6418, 5753, 648, 1475, 7832, 5836, 8983, 1236, 2511, 5878, 9237, 4982, 6846, 818, 2484, 779, 6092, 7585, 9457, 7383, 9587, 9543, 5051, 3616, 3024, 4163, 7346, 5012, 524, 3351, 1789, 9465, 3321, 8273, 8702, 5006, 2445, 5703, 4775, 9840, 7705, 6084, 9995, 8293, 7719, 9513, 591, 4471, 6131, 6768, 298, 6507, 737, 6491, 4435, 5899, 9521, 3926, 7809, 6585, 3289, 6873, 916, 6866, 9421, 2524, 4009, 5724, 5381, 6122, 9963, 9631, 4570, 4833, 2541, 1267, 5538, 3751, 6203, 7100, 394, 4406, 8489, 5178, 4426, 9712, 8798, 947, 5860, 3029, 9068, 7803, 3869, 2584, 5691, 5310, 6429, 8275, 7220, 4530, 6774, 243, 7323, 5081, 6192, 892, 3016, 8827, 1749, 1186, 6597, 1568, 5237, 1894, 9054, 5725, 9913, 1319, 32, 4086, 9428, 2843, 5719, 8714, 7069, 450, 2559, 2969, 2623, 7468, 595, 9074, 6218, 3974, 1903, 8143, 3216, 3706, 4467, 9217, 6877, 7577, 1740, 3979, 3097, 7709, 3699, 3310, 2572, 6608, 7326, 3662, 3675, 4701, 9, 6822, 6070, 6114, 1531, 2294, 4056, 1214, 1115, 7252, 1486, 9450, 306, 9957, 2536, 1145, 3910, 157, 6856, 3163, 2121, 6391, 7906, 9895, 1299, 28, 2205, 5892, 8265, 5868, 3139, 7040, 3915, 2814, 2569, 1034, 1345, 2844, 7805, 7941, 5303, 6050, 7657, 4156, 9373, 3736, 2833, 4154, 8199, 8232, 2489, 9805, 8884, 1323, 2790, 2185, 8826, 1881, 6741, 1324, 3708, 6788, 4853, 9247, 9830, 2273, 650, 9811, 2965, 7851, 6190, 2382, 5223, 7068, 9856, 9752, 581, 7801, 1713, 5115, 361, 9611, 2809, 9372, 5746, 3782, 7235, 9972, 9772, 1183, 3615, 5675, 8377, 8208, 7921, 8102, 6884, 9541, 5842, 7297, 969, 7890, 5493, 7611, 7342, 8094, 1986, 6121, 5252, 2432, 8672, 3858, 3587, 2268, 4992, 8992, 1184, 9844, 2855, 676, 9463, 6925, 9883, 8519, 4886, 2538, 91, 1005, 2157, 3649, 1445, 1464, 1060, 9781, 2262, 9740, 9172, 3274, 1472, 9201, 1542, 6363, 9496, 3400, 3580, 666, 396, 2911, 7880, 9259, 7036, 9055, 1733, 9653, 3971, 2075, 7193, 4922, 9757, 5798, 179, 5818, 2580, 9329, 2330, 5204, 8367, 3072, 41, 4036, 710, 7071, 7057, 5100, 7636, 4809, 3905, 7540, 5961, 3308, 5618, 4434, 3147, 8639, 2909, 1420, 469, 9059, 1497, 841, 3916, 4314, 7093, 1320, 4175, 5563, 2557, 6864, 3551, 5102, 6209, 924, 4994, 3747, 2510, 1166, 9145, 853, 9427, 8624, 1541, 9655, 6107, 2614, 7028, 1773, 9102, 6408, 7138, 1116, 1460, 2653, 686, 5177, 895, 1363, 1056, 1917, 5395, 9827, 8911, 6766, 4168, 7680, 1477, 2760, 3825, 5865, 197, 8150, 3557, 1352, 8305, 1650, 7821, 5581, 7619, 1913, 6403, 585, 2492, 6524, 2351, 3683, 2280, 2261, 1185, 7041, 1648, 4398, 8542, 5586, 4310, 2500, 5736, 436, 9283, 1693, 9700, 8297, 2948, 5642, 5124, 4773, 3947, 7152, 3419, 6033, 6332, 6110, 7864, 9636, 7858, 9602, 1455, 7621, 353, 9083, 3911, 6260, 3709, 1652, 54, 3848, 1919, 5123, 4138, 1504, 4827, 4744, 748, 572, 3678, 459, 6053, 3061, 4186, 4979, 7526, 9876, 9064, 2041, 9168, 2905, 5792, 3223, 9514, 7976, 9021, 166, 3620, 7097, 2972, 386, 3835, 3888, 2025, 4989, 5150, 433, 7393, 8420, 5803, 6795, 728, 5044, 6875, 7242, 6645, 8745, 2181, 258, 9506, 8024, 9178, 5568, 4007, 6457, 109, 3811, 2275, 7884, 289, 8721, 5610, 9279, 5048, 7828, 3194, 5810, 2085, 981, 2095, 3975, 1393, 9674, 4106, 3261, 8139, 257, 4721, 7742, 6056, 6130, 5574, 486, 409, 1532, 8918, 9544, 6826, 4948, 5995, 3530, 5975, 8129, 9489, 6169, 5727, 5503, 2270, 6775, 770, 7373, 1611, 8558, 5511, 9345, 87, 7169, 2196, 2709, 7116, 6578, 8251, 4238, 3611, 4745, 2325, 6113, 604, 713, 1824, 1530, 9190, 956, 8503, 4229, 8518, 6833, 4578, 4356, 1891, 8056, 4567, 9305, 2301, 2385, 899, 3721, 5341, 118, 3378, 4998, 9165, 4768, 6117, 5052, 4385, 7838, 5786, 385, 5111, 8453, 3941, 9268, 824, 651, 3828, 8187, 2782, 9672, 5388, 8388, 5949, 2457, 8524, 9911, 1051, 9134, 2171, 9726, 5306, 4397, 1091, 6715, 5483, 9635, 8964, 574, 8526, 85, 5917, 176, 5417, 5143, 7427, 3923, 248, 1513, 413, 2669, 263, 8088, 8744, 7279, 3691, 9637, 3109, 3543, 6485, 8406, 6297, 9751, 4335, 9188, 346, 2194, 3018, 9319, 2501, 3783, 2868, 1502, 8334, 8940, 4258, 1910, 8986, 6910, 3311, 5109, 4894, 939, 9860, 721, 7734, 5037, 5852, 6181, 7688, 6663, 2283, 9713, 527, 5235, 7532, 3636, 6557, 1408, 9892, 6860, 6994, 7431, 6060, 6435, 6083, 2278, 6288, 7083, 2360, 6001, 9406, 7969, 4308, 7173, 5084, 5844, 5626, 255, 8584, 8324, 7241, 2225, 5149, 2617, 5127, 3361, 4891, 5481, 2722, 2567, 8527, 8794, 2108, 6280, 7601, 2350, 984, 1714, 2610, 7296, 7363, 1764, 3422, 3770, 4748, 6626, 9559, 3544, 3443, 9106, 2729, 8485, 7850, 5455, 9001, 1172, 2216, 7470, 5083, 781, 3642, 8371, 6086, 5616, 3068, 9645, 9272, 941, 2277, 4940, 3629, 1775, 8083, 5274, 4579, 2552, 1777, 5498, 8032, 8186, 9985, 4837, 98, 923, 3707, 505, 3421, 8693, 2531, 7424, 1857, 3867, 3951, 2233, 5369, 1252, 9764, 8876, 5935, 6349, 937, 3512, 7285, 8650, 6299, 4070, 211, 373, 5950, 2687, 2009, 48, 2329, 3028, 7154, 1594, 7179, 5665, 3697, 2402, 6618, 1743, 6438, 4008, 5653, 1573, 5705, 9663, 3001, 12, 6, 6271, 6749, 6975, 2887, 9570, 5071, 2604, 8361, 6229, 6214, 6787, 3451, 7306, 7595, 8398, 4152, 1128, 2576, 8546, 5035, 476, 3155, 7451, 8712, 1133, 9834, 1516, 1438, 4969, 462, 5510, 5890, 9547, 7962, 912, 1944, 6224]

In [77]:
with open('randlist.pkl', 'wb') as f:
    pickle.dump(randlist, f)

In [78]:
with open('randlist.pkl', 'rb') as f:
    loaded = pickle.load(f)

print(loaded)

[1372, 7392, 9046, 1933, 3632, 271, 7110, 3813, 8456, 7248, 6539, 7840, 6622, 11, 9961, 4945, 8376, 5017, 5894, 18, 4450, 4380, 3434, 3660, 6710, 8174, 5332, 9809, 3990, 2289, 8590, 2251, 2713, 5016, 4105, 9545, 477, 496, 6761, 3573, 9940, 3215, 9782, 1308, 8863, 4625, 6276, 2624, 7508, 8595, 2411, 8602, 3677, 6629, 2499, 5706, 8580, 911, 4785, 6469, 4015, 7174, 4784, 49, 5557, 2243, 9682, 9395, 5436, 2419, 8095, 1895, 1194, 3689, 4765, 2908, 1705, 8836, 5364, 3818, 3745, 6028, 9274, 7031, 3714, 1822, 8014, 7495, 5322, 1474, 1590, 8705, 2106, 8671, 1587, 439, 4614, 1187, 4679, 6361, 4027, 5094, 7445, 6839, 2853, 943, 4133, 8307, 4011, 3631, 2528, 8760, 7752, 9344, 7340, 5889, 3288, 7940, 8112, 7491, 3444, 4220, 470, 1768, 7589, 7989, 6696, 9881, 9467, 2035, 9446, 6198, 233, 2426, 3952, 6962, 2860, 1791, 4514, 2690, 465, 6338, 7423, 9850, 7606, 6246, 6418, 5753, 648, 1475, 7832, 5836, 8983, 1236, 2511, 5878, 9237, 4982, 6846, 818, 2484, 779, 6092, 7585, 9457, 7383, 9587, 9543, 5051, 3616, 3024, 4163, 7346, 5012, 524, 3351, 1789, 9465, 3321, 8273, 8702, 5006, 2445, 5703, 4775, 9840, 7705, 6084, 9995, 8293, 7719, 9513, 591, 4471, 6131, 6768, 298, 6507, 737, 6491, 4435, 5899, 9521, 3926, 7809, 6585, 3289, 6873, 916, 6866, 9421, 2524, 4009, 5724, 5381, 6122, 9963, 9631, 4570, 4833, 2541, 1267, 5538, 3751, 6203, 7100, 394, 4406, 8489, 5178, 4426, 9712, 8798, 947, 5860, 3029, 9068, 7803, 3869, 2584, 5691, 5310, 6429, 8275, 7220, 4530, 6774, 243, 7323, 5081, 6192, 892, 3016, 8827, 1749, 1186, 6597, 1568, 5237, 1894, 9054, 5725, 9913, 1319, 32, 4086, 9428, 2843, 5719, 8714, 7069, 450, 2559, 2969, 2623, 7468, 595, 9074, 6218, 3974, 1903, 8143, 3216, 3706, 4467, 9217, 6877, 7577, 1740, 3979, 3097, 7709, 3699, 3310, 2572, 6608, 7326, 3662, 3675, 4701, 9, 6822, 6070, 6114, 1531, 2294, 4056, 1214, 1115, 7252, 1486, 9450, 306, 9957, 2536, 1145, 3910, 157, 6856, 3163, 2121, 6391, 7906, 9895, 1299, 28, 2205, 5892, 8265, 5868, 3139, 7040, 3915, 2814, 2569, 1034, 1345, 2844, 7805, 7941, 5303, 6050, 7657, 4156, 9373, 3736, 2833, 4154, 8199, 8232, 2489, 9805, 8884, 1323, 2790, 2185, 8826, 1881, 6741, 1324, 3708, 6788, 4853, 9247, 9830, 2273, 650, 9811, 2965, 7851, 6190, 2382, 5223, 7068, 9856, 9752, 581, 7801, 1713, 5115, 361, 9611, 2809, 9372, 5746, 3782, 7235, 9972, 9772, 1183, 3615, 5675, 8377, 8208, 7921, 8102, 6884, 9541, 5842, 7297, 969, 7890, 5493, 7611, 7342, 8094, 1986, 6121, 5252, 2432, 8672, 3858, 3587, 2268, 4992, 8992, 1184, 9844, 2855, 676, 9463, 6925, 9883, 8519, 4886, 2538, 91, 1005, 2157, 3649, 1445, 1464, 1060, 9781, 2262, 9740, 9172, 3274, 1472, 9201, 1542, 6363, 9496, 3400, 3580, 666, 396, 2911, 7880, 9259, 7036, 9055, 1733, 9653, 3971, 2075, 7193, 4922, 9757, 5798, 179, 5818, 2580, 9329, 2330, 5204, 8367, 3072, 41, 4036, 710, 7071, 7057, 5100, 7636, 4809, 3905, 7540, 5961, 3308, 5618, 4434, 3147, 8639, 2909, 1420, 469, 9059, 1497, 841, 3916, 4314, 7093, 1320, 4175, 5563, 2557, 6864, 3551, 5102, 6209, 924, 4994, 3747, 2510, 1166, 9145, 853, 9427, 8624, 1541, 9655, 6107, 2614, 7028, 1773, 9102, 6408, 7138, 1116, 1460, 2653, 686, 5177, 895, 1363, 1056, 1917, 5395, 9827, 8911, 6766, 4168, 7680, 1477, 2760, 3825, 5865, 197, 8150, 3557, 1352, 8305, 1650, 7821, 5581, 7619, 1913, 6403, 585, 2492, 6524, 2351, 3683, 2280, 2261, 1185, 7041, 1648, 4398, 8542, 5586, 4310, 2500, 5736, 436, 9283, 1693, 9700, 8297, 2948, 5642, 5124, 4773, 3947, 7152, 3419, 6033, 6332, 6110, 7864, 9636, 7858, 9602, 1455, 7621, 353, 9083, 3911, 6260, 3709, 1652, 54, 3848, 1919, 5123, 4138, 1504, 4827, 4744, 748, 572, 3678, 459, 6053, 3061, 4186, 4979, 7526, 9876, 9064, 2041, 9168, 2905, 5792, 3223, 9514, 7976, 9021, 166, 3620, 7097, 2972, 386, 3835, 3888, 2025, 4989, 5150, 433, 7393, 8420, 5803, 6795, 728, 5044, 6875, 7242, 6645, 8745, 2181, 258, 9506, 8024, 9178, 5568, 4007, 6457, 109, 3811, 2275, 7884, 289, 8721, 5610, 9279, 5048, 7828, 3194, 5810, 2085, 981, 2095, 3975, 1393, 9674, 4106, 3261, 8139, 257, 4721, 7742, 6056, 6130, 5574, 486, 409, 1532, 8918, 9544, 6826, 4948, 5995, 3530, 5975, 8129, 9489, 6169, 5727, 5503, 2270, 6775, 770, 7373, 1611, 8558, 5511, 9345, 87, 7169, 2196, 2709, 7116, 6578, 8251, 4238, 3611, 4745, 2325, 6113, 604, 713, 1824, 1530, 9190, 956, 8503, 4229, 8518, 6833, 4578, 4356, 1891, 8056, 4567, 9305, 2301, 2385, 899, 3721, 5341, 118, 3378, 4998, 9165, 4768, 6117, 5052, 4385, 7838, 5786, 385, 5111, 8453, 3941, 9268, 824, 651, 3828, 8187, 2782, 9672, 5388, 8388, 5949, 2457, 8524, 9911, 1051, 9134, 2171, 9726, 5306, 4397, 1091, 6715, 5483, 9635, 8964, 574, 8526, 85, 5917, 176, 5417, 5143, 7427, 3923, 248, 1513, 413, 2669, 263, 8088, 8744, 7279, 3691, 9637, 3109, 3543, 6485, 8406, 6297, 9751, 4335, 9188, 346, 2194, 3018, 9319, 2501, 3783, 2868, 1502, 8334, 8940, 4258, 1910, 8986, 6910, 3311, 5109, 4894, 939, 9860, 721, 7734, 5037, 5852, 6181, 7688, 6663, 2283, 9713, 527, 5235, 7532, 3636, 6557, 1408, 9892, 6860, 6994, 7431, 6060, 6435, 6083, 2278, 6288, 7083, 2360, 6001, 9406, 7969, 4308, 7173, 5084, 5844, 5626, 255, 8584, 8324, 7241, 2225, 5149, 2617, 5127, 3361, 4891, 5481, 2722, 2567, 8527, 8794, 2108, 6280, 7601, 2350, 984, 1714, 2610, 7296, 7363, 1764, 3422, 3770, 4748, 6626, 9559, 3544, 3443, 9106, 2729, 8485, 7850, 5455, 9001, 1172, 2216, 7470, 5083, 781, 3642, 8371, 6086, 5616, 3068, 9645, 9272, 941, 2277, 4940, 3629, 1775, 8083, 5274, 4579, 2552, 1777, 5498, 8032, 8186, 9985, 4837, 98, 923, 3707, 505, 3421, 8693, 2531, 7424, 1857, 3867, 3951, 2233, 5369, 1252, 9764, 8876, 5935, 6349, 937, 3512, 7285, 8650, 6299, 4070, 211, 373, 5950, 2687, 2009, 48, 2329, 3028, 7154, 1594, 7179, 5665, 3697, 2402, 6618, 1743, 6438, 4008, 5653, 1573, 5705, 9663, 3001, 12, 6, 6271, 6749, 6975, 2887, 9570, 5071, 2604, 8361, 6229, 6214, 6787, 3451, 7306, 7595, 8398, 4152, 1128, 2576, 8546, 5035, 476, 3155, 7451, 8712, 1133, 9834, 1516, 1438, 4969, 462, 5510, 5890, 9547, 7962, 912, 1944, 6224]